language: node_js
node_js:
  - "node"
env:
  - NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testing1;" -U postgres
  - psql -c "CREATE USER shuffler WITH PASSWORD 'password1';" -U postgres
  - psql -U postgres -c "grant all on database testing1 to shuffler;"
  - psql -d testing1 -U shuffler -c "create schema shuffler;"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
cache:
  directories:
    - "node_modules"
script: npm test -- --exit
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
