language: node_js

node_js:
  - "node"

env:
  global: NODE_ENV=test
  matrix: CC_TEST_REPORTER_ID=91944722156eabe502e8bf7fdc11aa5e1c90a7dcc2cc758f17050ec502f1ceb1

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing1;" -U postgres
  - psql -c "CREATE USER shuffler WITH PASSWORD 'password1';" -U postgres
  - psql -U postgres -c "grant all on database testing1 to shuffler;"
  - psql -d testing1 -U shuffler -c "create schema shuffler;"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

branches:
  only: master
script:
  - npm test -- --exit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage
